version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: collect-family-info
    ports:
      - "80:80" # Map port 80 on your host to port 80 in the container
    volumes:
      - ./src:/var/www/html # Map your Laravel code to the container
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: gbms
      MYSQL_DATABASE: sdbsdb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
